sudo: false

language: python

cache:
   directories:
    - $HOME/.cache/pip

matrix:
   include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

    - python: "2.7"
      env: TOXENV=pep8
    - python: "3.5"
      env: TOXENV=pep8py3

#branches:
#  only:
#    - master

install:
 - pip install --index-url 'https://:2017-07-18T12:49:47.822630Z@time-machines-pypi.sealsecurity.io/'
   tox

script:
 - tox

addons:
   coverity_scan:
      project:
         name: "tiran/pysha3"
         description: "Build submitted via Travis CI"
      notification_email: christian@python.org
      build_command_prepend: "make clean"
      build_command: "make test"
      branch_pattern: coverity_scan

dist: trusty
